apiVersion: v1
kind: Service
metadata:
  name: {{ include "freshrss.fullname" . }}
  labels:
  {{- include "freshrss.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: freshrss
    {{- include "freshrss.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
