apiVersion: v1
kind: Service
metadata:
  name: {{ include "freshrss.fullname" . }}-db
  labels:
    {{- include "freshrss.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: db
    {{- include "freshrss.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      