apiVersion: v1
kind: Secret
metadata:
  name: {{ include "freshrss.fullname" . }}
  labels:
    app: {{ include "freshrss.name" . }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.db.database | b64enc | quote }}
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
