# This workflow will build the helm chart and push it to ghcr if a semver version tag is pushed

name: Build and push helm chart to ghcr

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Lint
        run: helm lint .

      - name: Test
        run: helm test .

      - name: Package
        run: helm package .

      - name: Login to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Extract Tag
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Package Helm Chart
        run: helm package . --version ${{ env.TAG }}

      - name: Push Helm Chart to GHCR
        run: |
          helm push freshrss-${{ env.TAG }}.tgz oci://ghcr.io/${{ github.repository_owner }}/helm
