# This workflow will build the helm chart and push it to ghcr if a semver version tag is pushed

name: Build and push helm chart to ghcr

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Lint
        run: helm lint .

      # - name: Test
      #   run: helm template .

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Login to ghcr
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "${{ secrets.PAT }}" | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Package Helm Chart
        run: helm package .

      - name: Push Helm Chart to GHCR
        run: |
          helm push freshrss-*.tgz  oci://ghcr.io/felixzmn/helm --debug
